version: '3'

services:
  db:
    image: postgres:latest
    container_name: dbcont
    environment:
      - POSTGRES_DB=server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminbmw
    networks:
      - bmw
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: openjdk:17-jre-slim  
    container_name: spring_security_app
    depends_on:
      - db
    environment:
      - DB_CONNECT=jdbc:postgresql://db:5432/server
      - DB_PASSWORD=adminbmw
      - DB_USER=postgres
    networks:
      - bmw
    ports:
      - "8080:8080"
    volumes:
      - ./app.jar:/app/app.jar  
    command: java -jar /app/app.jar  

networks:
  bmw:
    driver: bridge

volumes:
  postgres_data:
