apiVersion: v1
kind: Secret
metadata:
  name: spring-security-app
type: Opaque
data:
  DB_CONNECT: amRiYzpwb3N0Z3Jlc3FsOi8vMTkzLjEyNC4xMTIuMTUzOjU0MzMvc2VydmVy
  DB_PASSWORD: YWRtaW5ibXc=
  DB_USER: cG9zdGdyZXM=
