apiVersion: v1
kind: Service
metadata:
  name: spring-security-app
spec:
  selector:
    app: spring-security-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
