name: CI
on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker image
        run: |
          docker build -t m004ka/SpringUserApplication:latest .


      - name: Push Docker image to Docker Hub
        run: |
          docker push m004ka/SpringUserApplication:latest

      - name: Verify Docker image is pushed
        run: |
          docker pull m004ka/SpringUserApplication:latest

